// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ2ZBEsTPWo978XvUZZHJPk57NakgA51A',
    appId: '1:216884980572:web:67dd80e2bf338b807eef99',
    messagingSenderId: '216884980572',
    projectId: 'e-com-app-38770',
    authDomain: 'e-com-app-38770.firebaseapp.com',
    storageBucket: 'e-com-app-38770.appspot.com',
    measurementId: 'G-JSWFSEYQ4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7o3j1RSBYZ7VAbSPUzQtn78xZpef7JJY',
    appId: '1:216884980572:android:a4cd853f0cc6f5247eef99',
    messagingSenderId: '216884980572',
    projectId: 'e-com-app-38770',
    storageBucket: 'e-com-app-38770.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6HDMhsSRD_Xay8ntbgHcnwFq5h4iR9MI',
    appId: '1:216884980572:ios:3ddcb6a68aaa30c57eef99',
    messagingSenderId: '216884980572',
    projectId: 'e-com-app-38770',
    storageBucket: 'e-com-app-38770.appspot.com',
    iosBundleId: 'com.example.eComFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6HDMhsSRD_Xay8ntbgHcnwFq5h4iR9MI',
    appId: '1:216884980572:ios:10db1d4e03ddbf657eef99',
    messagingSenderId: '216884980572',
    projectId: 'e-com-app-38770',
    storageBucket: 'e-com-app-38770.appspot.com',
    iosBundleId: 'com.example.eComFirebase.RunnerTests',
  );
}
